Switched to inline orb for circleci config.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,178 +1,421 @@
-# Ruby CircleCI 2.0 configuration file
-#
-# Check https://circleci.com/docs/2.0/language-ruby/ for more details
-#
 version: 2.1
-parameters:
-  ruby-version:
-    type: string
-    default: "3.0.3"
-  postgres-version:
-    type: string
-    default: "11.13"
-executors:
-  docker-publisher:
-    environment:
-      IMAGE_NAME: suldlss/suri-rails
-    docker:
-    - image: cimg/base
-jobs:
-  test:
-    docker:
-      - image: 'cimg/ruby:<< pipeline.parameters.ruby-version >>-node'
+orbs:
+  ruby-rails:
+    orbs:
+      docker: circleci/docker@2.0.1
+      node: circleci/node@3.0
+      ruby: circleci/ruby@1.2.0
+      browser-tools: circleci/browser-tools@1.2.3
+    references:
+      ruby-version-ref: &ruby-version-ref '2.7.5'
+      postgres-version-ref: &postgres-version-ref '11.13'
+      ruby-executor-refs: &ruby-executor-refs
+        image: 'cimg/ruby:<< parameters.ruby-tag >>-node'
         environment:
-          BUNDLE_JOBS: 3
-          BUNDLE_RETRY: 3
-          BUNDLE_PATH: vendor/bundle
-          PGHOST: 127.0.0.1
-          PGUSER: circleci-demo-ruby
-          PGPASSWORD: sekret
+          BUNDLE_JOBS: '3'
+          BUNDLE_RETRY: '3'
           RAILS_ENV: test
-          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
-      - image: 'cimg/postgres:<< pipeline.parameters.postgres-version >>'
+          PAGER: cat
+          TZ: "America/Los_Angeles"
+      postgres-executor-refs: &postgres-executor-refs
+        image: 'cimg/postgres:<< parameters.postgres-tag >>'
         environment:
           POSTGRES_USER: postgres
-          POSTGRES_DB: suri
           POSTGRES_PASSWORD: sekret
-
-    working_directory: ~/repo
-
-    steps:
-      - checkout
-
-      - run:
-          name: Validate API specification
-          command: |
-            sudo npm install -g openapi-enforcer-cli
-            result=$(openapi-enforcer validate openapi.yml)
-            [[ $result =~ "Document is valid" ]] && {
-            echo "Validation good"
-            exit 0
-            } || {
-            echo $result
-            exit 1
-            }
-
-      - run:
-          name: Install/Upgrade bundler
-          command: gem install bundler -v 2.3.4
-
-      - run:
-          name: Which bundler?
-          command: bundle -v
-
-      - run:
-          name: Install dependencies
-          command: bundle check || bundle install
-
-      - run:
-          name: Run code linter & style checker
-          command: bundle exec rubocop
-
-      - run:
-          name: Wait for DB
-          command: dockerize -wait tcp://localhost:5432 -timeout 1m
-
-      - run:
-          name: Set up database
-          command: bin/rails db:test:prepare
-
-      - run:
-          name: Setup Code Climate test-reporter
-          command: |
-            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
-            chmod +x ./cc-test-reporter
-            ./cc-test-reporter before-build
-
-      - run:
-          name: rspec
-          command: bundle exec rspec
-
-      - run:
-          name: upload test coverage report to Code Climate
-          command: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
-
-  build-image:
-    executor: docker-publisher
-    steps:
-      - checkout
-      - setup_remote_docker
-      - run:
-          name: Build Docker image
-          command: |
-            docker build -t $IMAGE_NAME:latest .
-      - run:
-          name: Archive Docker image
-          command: |
-            docker save -o app_image.tar $IMAGE_NAME
-      - persist_to_workspace:
-          root: .
-          paths:
-            - ./app_image.tar
-  publish-latest:
-    executor: docker-publisher
-    steps:
-      - attach_workspace:
-          at: /tmp/workspace
-      - setup_remote_docker
-      - run:
-          name: Load archived Docker image
-          command: |
-            docker load -i /tmp/workspace/app_image.tar
-      - run:
-          name: Publish Docker Image to Docker Hub
-          command: |
-            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
-            docker push $IMAGE_NAME:latest
-  publish-tag:
-    executor: docker-publisher
-    steps:
-      - attach_workspace:
-          at: /tmp/workspace
-      - setup_remote_docker
-      - run:
-          name: Load archived Docker image
-          command: |
-            docker load -i /tmp/workspace/app_image.tar
-      - run:
-          name: Publish Docker Image to Docker Hub
-          command: |
-            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
-            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_TAG
-            docker push $IMAGE_NAME:$CIRCLE_TAG
-
-workflows:
-  version: 2
-
-  test:
+      ruby-tag-parameter-ref: &ruby-tag-parameter-ref
+        default: *ruby-version-ref
+        description: The `cimg/ruby` Docker image version tag.
+        type: string
+      postgres-tag-parameter-ref: &postgres-tag-parameter-ref
+          default: *postgres-version-ref
+          description: The `cimg/postgres` Docker image version tag.
+          type: string
+    executors:
+      ruby:
+        description: Ruby-only executor.
+        parameters:
+          ruby-tag:
+            <<: *ruby-tag-parameter-ref
+        docker:
+          - <<: *ruby-executor-refs
+      ruby-postgres:
+        description: Ruby and postgres-only executor.
+        parameters:
+          ruby-tag:
+            <<: *ruby-tag-parameter-ref
+          postgres-tag:
+            <<: *postgres-tag-parameter-ref
+        docker:
+          - <<: *ruby-executor-refs        
+          - <<: *postgres-executor-refs
+      ruby-postgres-redis:
+        description: Ruby, postgres, and redis-only executor.
+        parameters:
+          ruby-tag:
+            <<: *ruby-tag-parameter-ref
+          postgres-tag:
+            <<: *postgres-tag-parameter-ref
+        docker:
+          - <<: *ruby-executor-refs
+          - <<: *postgres-executor-refs
+          - image: circleci/redis:3
+    commands:
+      gem-install-deps:
+        description: Install dependencies without using deployment mode (suitable for gems)
+        steps:
+          - run:
+              name: Bundle Install
+              command: bundle check || bundle install
+      test:
+        description: Runs rspec wrapped with code climate
+        parameters:
+          cc-test-reporter-id:
+            default: CC_TEST_REPORTER_ID
+            description: |
+              Name of environment variable storing your Code Climate reporter test id
+            type: env_var_name
+        steps:
+          - run:
+              name: Setup Code Climate test-reporter
+              command: |
+                curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
+                chmod +x ./cc-test-reporter
+                ./cc-test-reporter before-build
+          - ruby/rspec-test
+          - run:
+              name: upload test coverage report to Code Climate
+              command: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $? -r $<< parameters.cc-test-reporter-id >>
+      validate-api:
+        description: Validate openapi specification
+        steps:
+          - run:
+              name: Validate API specification
+              command: |
+                sudo npm install -g openapi-enforcer-cli
+                result=$(openapi-enforcer validate openapi.yml)
+                [[ $result =~ "Document is valid" ]] && {
+                echo "Validation good"
+                exit 0
+                } || {
+                echo $result
+                exit 1
+                }
     jobs:
-    - test
-
+      lint:
+        parameters:
+          executor:
+            default: ruby
+            description: Executor to use for this job, defaults to ruby executor
+            type: executor
+        executor: << parameters.executor >>
+        steps:
+          - checkout
+          - gem-install-deps
+          - ruby/rubocop-check
+      test-gem:
+        parameters:
+          executor:
+            default: ruby
+            description: Executor to use for this job, defaults to ruby executor
+            type: executor
+          before-test:
+            default: []
+            description: Optional steps to run before running rspec
+            type: steps
+        executor: << parameters.executor >>
+        parallelism: 3
+        steps:
+          - checkout
+          - gem-install-deps
+          - run:
+              name: Install rspec_junit_formatter
+              command: bundle add rspec_junit_formatter
+          - when:
+              condition: << parameters.before-test >>
+              steps: << parameters.before-test >>
+          - test
+      test-rails:
+        parameters:
+          executor:
+            default: ruby-postgres
+            description: Executor to use for this job, defaults to ruby-postgres executor
+            type: executor
+          api-only:
+            default: false
+            description: True if this is an API only Rails app.
+            type: boolean
+          install-chrome:
+            default: false
+            description: True to install Chrome
+            type: boolean
+          db-prepare-command:
+            default: db:test:prepare
+            description: Database prepare command
+            type: string
+          before-test:
+            default: []
+            description: Optional steps to run before running rspec
+            type: steps
+        executor: << parameters.executor >>
+        parallelism: 3
+        steps:
+          - checkout
+          - ruby/install-deps
+          - when:
+              condition: << parameters.install-chrome >>
+              steps:
+                - browser-tools/install-chrome
+          - unless:
+              condition: << parameters.api-only >>
+              steps:
+                - node/install-packages:
+                    pkg-manager: yarn
+          - run:
+              command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
+              name: Wait for DB
+          - run:
+              name: Test prepare
+              command: bin/rails << parameters.db-prepare-command >>
+          - when:
+              condition: << parameters.before-test >>
+              steps: << parameters.before-test >>
+          - test
+      validate-api:
+        description: Validate openapi specification
+        executor: node/default
+        steps:
+          - checkout
+          - validate-api
+      docker-publish:
+        description: Build and deploy a Docker image
+        executor: docker/machine
+        parameters:
+          docker-password:
+            default: DOCKER_PASS
+            description: |
+              Name of environment variable storing your Docker password
+            type: env_var_name
+          docker-username:
+            default: DOCKER_USER
+            description: |
+              Name of environment variable storing your Docker username
+            type: env_var_name
+          dockerfile:
+            default: Dockerfile
+            description: 'Name of dockerfile to use, defaults to Dockerfile'
+            type: string
+          image:
+            description: Name of image to build
+            type: string
+          tag:
+            default: latest
+            description: 'Comma-separated list of image tags, defaults to latest'
+            type: string
+        steps:
+          - checkout
+          - docker/check:
+              docker-password: <<parameters.docker-password>>
+              docker-username: <<parameters.docker-username>>
+          - docker/build:
+              dockerfile: <<parameters.dockerfile>>
+              image: <<parameters.image>>
+              tag: <<parameters.tag>>
+          - docker/push:
+              image: <<parameters.image>>
+              tag: <<parameters.tag>>
+workflows:
   build:
     jobs:
-    - build-image:
-        filters:
-          branches:
-            only: master
-    - publish-latest:
-        requires:
-          - build-image
-        filters:
-          branches:
-            only: master
-  build-tags:
-    jobs:
-    - build-image:
-        filters:
-          tags:
-            only: /^[0-9]+\.[0-9]+\.[0-9]+/
-          branches:
-            ignore: /.*/
-    - publish-tag:
-        requires:
-          - build-image
-        filters:
-          tags:
-            only: /^[0-9]+\.[0-9]+\.[0-9]+/
-          branches:
-            ignore: /.*/
+      - ruby-rails/validate-api:
+          name: validate
+      - ruby-rails/lint:
+          name: lint
+      - ruby-rails/test-rails:
+          name: test
+          api-only: true
+      - ruby-rails/docker-publish:
+          context: dlss
+          name: publish-latest
+          image: suldlss/suri-rails
+          requires:
+            - validate
+            - lint
+            - test
+          filters:
+            branches:
+              only:
+                - main
+
+# parameters:
+#   ruby-version:
+#     type: string
+#     default: "3.0.3"
+#   postgres-version:
+#     type: string
+#     default: "11.13"
+# executors:
+#   docker-publisher:
+#     environment:
+#       IMAGE_NAME: suldlss/suri-rails
+#     docker:
+#     - image: cimg/base
+# jobs:
+#   test:
+#     docker:
+#       - image: 'cimg/ruby:<< pipeline.parameters.ruby-version >>-node'
+#         environment:
+#           BUNDLE_JOBS: 3
+#           BUNDLE_RETRY: 3
+#           BUNDLE_PATH: vendor/bundle
+#           PGHOST: 127.0.0.1
+#           PGUSER: circleci-demo-ruby
+#           PGPASSWORD: sekret
+#           RAILS_ENV: test
+#           NOKOGIRI_USE_SYSTEM_LIBRARIES: true
+#       - image: 'cimg/postgres:<< pipeline.parameters.postgres-version >>'
+#         environment:
+#           POSTGRES_USER: postgres
+#           POSTGRES_DB: suri
+#           POSTGRES_PASSWORD: sekret
+
+#     working_directory: ~/repo
+
+#     steps:
+#       - checkout
+
+#       - run:
+#           name: Validate API specification
+#           command: |
+#             sudo npm install -g openapi-enforcer-cli
+#             result=$(openapi-enforcer validate openapi.yml)
+#             [[ $result =~ "Document is valid" ]] && {
+#             echo "Validation good"
+#             exit 0
+#             } || {
+#             echo $result
+#             exit 1
+#             }
+
+#       - run:
+#           name: Install/Upgrade bundler
+#           command: gem install bundler -v 2.3.4
+
+#       - run:
+#           name: Which bundler?
+#           command: bundle -v
+
+#       - run:
+#           name: Install dependencies
+#           command: bundle check || bundle install
+
+#       - run:
+#           name: Run code linter & style checker
+#           command: bundle exec rubocop
+
+#       - run:
+#           name: Wait for DB
+#           command: dockerize -wait tcp://localhost:5432 -timeout 1m
+
+#       - run:
+#           name: Set up database
+#           command: bin/rails db:test:prepare
+
+#       - run:
+#           name: Setup Code Climate test-reporter
+#           command: |
+#             curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
+#             chmod +x ./cc-test-reporter
+#             ./cc-test-reporter before-build
+
+#       - run:
+#           name: rspec
+#           command: bundle exec rspec
+
+#       - run:
+#           name: upload test coverage report to Code Climate
+#           command: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
+
+#   build-image:
+#     executor: docker-publisher
+#     steps:
+#       - checkout
+#       - setup_remote_docker
+#       - run:
+#           name: Build Docker image
+#           command: |
+#             docker build -t $IMAGE_NAME:latest .
+#       - run:
+#           name: Archive Docker image
+#           command: |
+#             docker save -o app_image.tar $IMAGE_NAME
+#       - persist_to_workspace:
+#           root: .
+#           paths:
+#             - ./app_image.tar
+#   publish-latest:
+#     executor: docker-publisher
+#     steps:
+#       - attach_workspace:
+#           at: /tmp/workspace
+#       - setup_remote_docker
+#       - run:
+#           name: Load archived Docker image
+#           command: |
+#             docker load -i /tmp/workspace/app_image.tar
+#       - run:
+#           name: Publish Docker Image to Docker Hub
+#           command: |
+#             echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
+#             docker push $IMAGE_NAME:latest
+#   publish-tag:
+#     executor: docker-publisher
+#     steps:
+#       - attach_workspace:
+#           at: /tmp/workspace
+#       - setup_remote_docker
+#       - run:
+#           name: Load archived Docker image
+#           command: |
+#             docker load -i /tmp/workspace/app_image.tar
+#       - run:
+#           name: Publish Docker Image to Docker Hub
+#           command: |
+#             echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
+#             docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_TAG
+#             docker push $IMAGE_NAME:$CIRCLE_TAG
+
+# workflows:
+#   version: 2
+
+#   test:
+#     jobs:
+#     - test
+
+#   build:
+#     jobs:
+#     - build-image:
+#         filters:
+#           branches:
+#             only: master
+#     - publish-latest:
+#         requires:
+#           - build-image
+#         filters:
+#           branches:
+#             only: master
+#   build-tags:
+#     jobs:
+#     - build-image:
+#         filters:
+#           tags:
+#             only: /^[0-9]+\.[0-9]+\.[0-9]+/
+#           branches:
+#             ignore: /.*/
+#     - publish-tag:
+#         requires:
+#           - build-image
+#         filters:
+#           tags:
+#             only: /^[0-9]+\.[0-9]+\.[0-9]+/
+#           branches:
+#             ignore: /.*/
